/**
 * This code was generated by Builder.io.
 */
import * as React from 'react';
import Image from 'next/image';

interface CourseCardProps {
  imageUrl: string;
  title: string;
  targetAudience: string;
  likeIconUrl: string;
  dislikeIconUrl: string;
}

const CourseCard: React.FC<CourseCardProps> = ({
  imageUrl,
  title,
  targetAudience,
  likeIconUrl,
  dislikeIconUrl,
}) => {
  return (
    <article className="flex flex-col grow w-full bg-white rounded-xl shadow-lg max-md:mt-9">
      <Image src={imageUrl} alt={title} width={500} height={200} />
      <div className="text-xs font-bold leading-5 text-center text-orange-400">
        Based on interest
      </div>
      <div className="flex flex-col p-3">
        <h3 className="text-sm font-semibold leading-5 text-neutral-900">
          {title}
        </h3>
        <div className="flex flex-col mt-4 text-xs font-semibold leading-4">
          <div className="text-gray-500">Target Audience</div>
          <div className="flex flex-col justify-center mt-1.5 whitespace-nowrap text-stone-500">
            <div className="flex flex-col flex-wrap justify-center content-center">
              <div className="justify-center px-1.5 py-0.5 bg-white rounded border border-solid border-stone-300">
                {targetAudience}
              </div>
            </div>
          </div>
        </div>
        <div className="flex gap-5 mt-4 w-full">
          <div className="flex-1 text-xs font-semibold leading-3 text-gray-500">
            Do you like this recommendation?
          </div>
          <div className="flex gap-2 my-auto">
            <Image
              src={likeIconUrl}
              alt="Like"
              width={16}
              height={16}
              className="shrink-0 w-4 aspect-square"
            />
            <Image
              src={dislikeIconUrl}
              alt="Dislike"
              width={16}
              height={16}
              className="shrink-0 w-4 aspect-square"
            />
          </div>
        </div>
      </div>
    </article>
  );
};

export default CourseCard;
