/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

interface DateTimeProps {
  dateTime: string;
}

function DateTime({ dateTime }: DateTimeProps) {
  return (
    <time className="flex justify-center items-start px-6 py-3 max-md:px-5" dateTime={dateTime}>
      {dateTime}
    </time>
  );
}

export default function MyComponent() {
  return (
    <DateTime dateTime="2023-11-10T13:00:00+07:00">
      10 Nov 2023, 13:00 WIB
    </DateTime>
  );
}