/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

interface CourseCardProps {
  image: string;
  category: string;
  title: string;
  targetAudience: string;
}

const CourseCard: React.FC<CourseCardProps> = ({ image, category, title, targetAudience }) => {
  return (
    <div className="flex flex-col grow w-full bg-white rounded-xl shadow-lg max-md:mt-9">
      <img src={image} alt={title} className="w-full aspect-[2.5]" />
      <div className="text-xs font-bold leading-5 text-center text-orange-400">{category}</div>
      <div className="flex flex-col p-3">
        <h3 className="text-sm font-semibold leading-5 text-neutral-900">{title}</h3>
        <div className="flex flex-col mt-4 text-xs font-semibold leading-4">
          <div className="text-gray-500">Target Audience</div>
          <div className="flex flex-col justify-center mt-1.5 whitespace-nowrap text-stone-500">
            <div className="flex flex-col flex-wrap justify-center content-center mr-auto">
              <div className="justify-center px-1.5 py-0.5 bg-white rounded border border-solid border-stone-300">
                {targetAudience}
              </div>
            </div>
          </div>
        </div>
        <div className="flex gap-5 mt-4 w-full">
          <div className="flex-1 text-xs font-semibold leading-3 text-gray-500">
            Do you like this recommendation?
          </div>
          <div className="flex gap-2 my-auto">
            <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/ff64a048ffe7f53bc6c507d466da353fa3de8453b97ea7559ddba7286786c5d4?apiKey=97692b0d53e648149f11861270a3eda7&" alt="Thumbs up icon" className="shrink-0 w-4 aspect-square" />
            <img src="https://cdn.builder.io/api/v1/image/assets/TEMP/d94aa71ebcb4bcb7ad2a143afb30bd5961fc6d1c99a8e1fc78ea402d5a1a58ab?apiKey=97692b0d53e648149f11861270a3eda7&" alt="Thumbs down icon" className="shrink-0 w-4 aspect-square" />
          </div>
        </div>
      </div>
    </div>
  );
};

const MyComponent: React.FC = () => {
  const courses = [
    {
      image: "https://cdn.builder.io/api/v1/image/assets/TEMP/0f8459184301344dd57d1917600a9aca1501f06ea66d036319a82d10dacb8c84?apiKey=97692b0d53e648149f11861270a3eda7&",
      category: "Based on interest",
      title: "Complete python developer for zero to hero",
      targetAudience: "Staff",
    },
    {
      image: "https://cdn.builder.io/api/v1/image/assets/TEMP/ccb64d276a688e02ed9bfffa61142c052d11e1332416ee9353577b62eb6706d2?apiKey=97692b0d53e648149f11861270a3eda7&",
      category: "Based on interest",
      title: "Complete python developer for zero to hero",
      targetAudience: "Staff",
    },
    {
      image: "https://cdn.builder.io/api/v1/image/assets/TEMP/588f46de73bf5d7d580261f136405572218f7e0661f59ed971e942742fbb020a?apiKey=97692b0d53e648149f11861270a3eda7&",
      category: "Based on course you finished",
      title: "Complete python developer for zero to hero", 
      targetAudience: "Staff",
    },
    {
      image: "https://cdn.builder.io/api/v1/image/assets/TEMP/f94fefc8569f49df7411dbd7657a57ef481b85cdc4c9ea0a705f882f9f99623a?apiKey=97692b0d53e648149f11861270a3eda7&",
      category: "Based on course you finished",
      title: "Complete python developer for zero to hero",
      targetAudience: "Staff",
    },
  ];

  return (
    <div className="flex flex-col max-md:max-w-full">
      <h2 className="text-xl font-bold leading-6 text-black max-md:max-w-full">Course that might you like</h2>
      <div className="justify-between mt-5 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col max-md:gap-0">
          {courses.map((course, index) => (
            <div key={index} className="flex flex-col w-3/12 max-md:ml-0 max-md:w-full">
              <CourseCard {...course} />
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default MyComponent;