/**
 * This code was generated by Builder.io.
 */
// **ROLE**
// Act like an expert software engineer writing a web application using Next.js, Tailwind CSS, and TypeScript.

// **GENERAL INSTRUCTIONS**
// - Choose a correct HTML semantic element when rendering a UI element, do not generalize all blocks as divs.
// - Do not print semicolons at the end of each statement, including import statements.
// - Use the Next.js Image component for images instead of the img tag, including converting srcset to src.

// **DETAILED INSTRUCTIONS**
// This page is a form with this specification 
// - 1 custom input text. At the end of this input, a button is attached to check the validity of this input
// - 4 input texts with toggleable disabled state. Disabled input has grey background. Enabled input has white background.
// - 1 select dropdown list. It has several options.
// - Cancel to go back
// - Save button to submit

// **SYSTEM INSTRUCTION**
// Before generating the code, at the start of each file, write this prompt instructions as commented code.

import * as React from "react"
import Navigation from "@/components/Navigation"

type InputFieldProps = {
  label: string
  value: string
  disabled?: boolean
}

const InputField: React.FC<InputFieldProps> = ({ label, value, disabled = true }) => (
  <div className="flex flex-col mt-4 leading-[143%] max-md:max-w-full">
    <label className="font-semibold tracking-normal text-gray-500 max-md:max-w-full">{label}</label>
    <input
      type="text"
      value={value}
      disabled={disabled}
      className={`justify-center items-start px-3 py-2.5 mt-1 text-gray-900 rounded-md border border-gray-300 border-solid max-md:pr-5 max-md:max-w-full ${
        disabled ? "bg-gray-200" : "bg-white"
      }`}
    />
  </div>
)

const EditAccountPage: React.FC = () => {
  return (
    <div className="flex flex-col justify-center pb-20 bg-gray-100">
      <div className="flex flex-col w-full max-md:max-w-full">
        <Navigation className="justify-center w-full max-md:max-w-full" />
        <header className="justify-center items-start py-4 pr-16 pl-28 w-full text-2xl font-semibold leading-6 text-gray-900 bg-white shadow-sm max-md:pr-5 max-md:pl-8 max-md:max-w-full">
          Edit Account
        </header>
        <main className="flex justify-center items-center px-16 py-10 w-full text-sm max-md:px-5 max-md:max-w-full">
          <form className="flex flex-col max-w-full w-[594px]">
            <div className="flex flex-col max-md:max-w-full">
              <div className="flex flex-col leading-[143%] max-md:max-w-full">
                <label htmlFor="nip" className="font-semibold tracking-normal text-gray-500 max-md:max-w-full">
                  NIP
                </label>
                <div className="flex gap-0 mt-1 text-gray-900 max-md:flex-wrap max-md:max-w-full">
                  <input
                    type="text"
                    id="nip"
                    value="1998121112391024"
                    className="flex-1 justify-center items-start px-3 py-2.5 whitespace-nowrap bg-gray-200 rounded-md border border-gray-300 border-solid max-md:pr-5 max-md:max-w-full"
                  />
                  <button
                    type="button"
                    className="justify-center py-2.5 pr-4 pl-4 font-medium bg-amber-300 rounded-none border border-gray-300 border-solid"
                  >
                    Check NIP
                  </button>
                </div>
              </div>
              <InputField label="Udomain" value="jane01" />
              <InputField label="Nama" value="Jane Cooper" />
              <InputField label="Email" value="jane.cooper@example.com" />
              <div className="flex flex-col mt-4 leading-[143%] max-md:max-w-full">
                <label htmlFor="cabang" className="font-semibold tracking-normal text-gray-500 max-md:max-w-full">
                  Cabang
                </label>
                <select
                  id="cabang"
                  className="justify-center items-start px-3 py-2.5 mt-1 text-gray-900 bg-gray-200 rounded-md border border-gray-300 border-solid max-md:pr-5 max-md:max-w-full"
                >
                  <option value="0001">0001 - Jakarta Pusat</option>
                </select>
              </div>
              <div className="flex flex-col mt-4 max-md:max-w-full">
                <label htmlFor="role" className="font-semibold tracking-normal leading-5 text-red-500 max-md:max-w-full">
                  Role<span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  id="role"
                  value="Admin Pusat"
                  disabled
                  className="justify-center items-start px-3 py-2.5 mt-1 text-gray-900 bg-gray-200 rounded-md border border-gray-300 border-solid leading-[143%] max-md:pr-5 max-md:max-w-full"
                />
              </div>
            </div>
            <div className="flex flex-col justify-center items-end px-16 mt-12 text-center text-gray-900 whitespace-nowrap leading-[143%] max-md:pl-5 max-md:mt-10 max-md:max-w-full">
              <div className="flex gap-2">
                <button type="button" className="justify-center px-6 py-2.5 font-medium bg-gray-200 rounded-[100px] max-md:px-5">
                  Cancel
                </button>
                <button type="submit" className="justify-center px-8 py-2.5 font-semibold tracking-normal bg-amber-300 rounded-[100px] max-md:px-5">
                  Save
                </button>
              </div>
            </div>
          </form>
        </main>
      </div>
    </div>
  )
}

export default EditAccountPage