/**
 * This code was generated by Builder.io.
 */
// **ROLE**
// Act like an expert software engineer writing a web application using Next.js, Tailwind CSS, and TypeScript.
// 
// **GENERAL INSTRUCTIONS**
// - Choose a correct HTML semantic element when rendering a UI element, do not generalize all blocks as divs.
// - Do not print semicolons at the end of each statement, including import statements.
// - Use the Next.js Image component for images instead of the img tag, including converting srcset to src.
// 
// **DETAILED INSTRUCTIONS**
// Enhance the code & results, by:
// - Vertically center the login card, but keep the login button width full inside the card.
// - Apply this linear gradient background: **linear-gradient(119deg, #1D99D7 0%, #843A8D 100%)** start from top-left until bottom-right.

import Image from "next/image"

type LoginCardProps = {
  logoSrc: string
  logoAlt: string
}

function LoginCard({ logoSrc, logoAlt }: LoginCardProps) {
  return (
    <main className="flex justify-center items-center px-16 py-20 h-screen max-md:px-5 bg-gradient-to-br from-[#1D99D7] to-[#843A8D]">
      <div className="flex flex-col justify-center px-4 py-12 max-w-full bg-white rounded-md w-[400px]">
        <Image
          src={logoSrc}
          alt={logoAlt}
          width={100}
          height={52}
          className="self-center max-w-full aspect-[1.92]"
        />
        <div className="flex flex-col mt-12 max-md:mt-10">
          <p className="self-center text-base leading-6 text-black">
            Employee/Teacher/Lecturer
          </p>
          <button className="px-4 py-3 mt-2 text-sm font-bold leading-4 text-white bg-indigo-500 rounded-md max-md:px-8">
            Login with BINUSIAN Account
          </button>
        </div>
      </div>
    </main>
  )
}

export default function MyComponent() {
  return <LoginCard logoSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/efb02bea3345c872486d184b34ba45550ef6a5f5889096dca4122aea2aa706f4?apiKey=d9be0c21d3f04234b0773d24d90d90a3&" logoAlt="Company logo" />
}